version: "3.9"

services:
    database:
        image: postgres
        container_name: fin_api
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=teste
            - POSTGRES_DB=fin_api
        volumes: 
            - pgdata:/data/postgres
    
volumes: 
    pgdata:
        driver: local